[package]
name = "rabbit-queue-configurer"
version = "0.1.0"
edition = "2021"

[dependencies]
hermes = { path = "../..", features = ["full"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
lapin = "2"